### ISSUE TITLE
Initial vision

### ISSUE THREAD

**Issue by pomek** [cksource/docs-builder#1]
After several weeks of a work, we have a vision how `docs-builder` will look and work. Name of this package is still a secret, so we called it as `docs-builder`. If you have a better proposal, feel free to share with us.

**The main goal of this package generates a documentation for a project.**

## Input

The engine needs a collection of files which will be foundations. The collection will contain:

1. `Guides` - single Markdown file (extension `*.md`) which represents a single guide.
2. `Samples` - a collection of three files - `*.md`, `*.html`, `*.js`:
  - `*.md` - Markdown files which describes a sample (similar to the guide),
  - `*.html` - HTML file which contains DOM,
  - `*.js` - JavaScript file which contains a behaviour.

### Pages

Documentation pages will be written using [Markdown](http://commonmark.org/). Each file will contain 2 sections (similar way like do [Jekyll](https://jekyllrb.com/docs/pages/)):
- Meta-data like page title, keywords, short description or `isDisqusAvailable` flag,
- Page content.

##### Example Markdown file:
```
title: Example
isDisqusAvailable: true

---

**Lorem** Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
```

## How it works?

The engine parses the input collection and builds necessary parts of a documentation. The whole process step by steps looks like below:

1. Prepare configuration.
2. Compile CSS / SASS / SCSS files.
3. Compile JS files (using Rollup).
4. Compile Markdown files to HTML.
5. Build Samples - connect three files (`*.md`, `*.html`, `*.js`) into one `*.html` file.
6. Save static files (CSS and JS).
7. Build navigation.
8. Save HTML files from point 5. and 6.
9. Copy static files (like fonts, images, etc).
10. Create main page for particular section (available under `/section/index.html`).
11. Create index page (available under `/index.html`).
12. Build API documentation (based on jsDoc).
13. Create ZIP archive (the documentation works offline).

## Output

The generated documentation contains three sections:

1. Guides - pure text
2. Samples - text with live example (preview available on jsFiddle)
3. API - generates from [jsDoc](http://usejsdoc.org/)

It is also the option to download the whole documentation as a zip archive.

Feel free to leave any feedback. At this moment every post can be helpful.

**Comment by pomek** [comment]
I prepared a schema with flow how Builder should work:

![builder flow](https://cloud.githubusercontent.com/assets/2270764/16304431/bf0f55b0-3955-11e6-8fe9-af2759144937.png)

**Comment by Reinmar** [comment]
That's a very good start. Nothing more to add, maybe except of a link to https://github.com/ckeditor/ckeditor5-design/issues/150. The documentation builder needs to comply with those requirements.

As for the diagram, it's a bit hard to understand now if that's the way in which builder will need to work. I'd rather propose starting with something minimal and seeing where it leads you. Especially things like configuration are hard to understand at this stage.

So let's keep all this open.

**Comment by pomek** [comment]
Few days ago we've decided to simplify few things. The schema above has been updated.

**Comment by pomek** [comment]
The first comment has been updated with current status of the project.
