### ISSUE TITLE
Code samples should not be wrapped

### ISSUE THREAD

**Issue by Reinmar** [cksource/docs-builder#10]
This looks bad:

![screen shot 2016-09-13 at 13 18 15](https://cloud.githubusercontent.com/assets/156149/18471958/90047f6c-79b4-11e6-9af5-339c79fe7e3c.png)

**Comment by pomek** [comment]
Fixed in #6.

The code container can be scrolled horizontal.

![image](https://cloud.githubusercontent.com/assets/2270764/18475655/9805b4b6-79c7-11e6-9fb4-e845fe3b8aff.png)
