### ISSUE TITLE
Is it possible to map headings in the guides that `#` generates h2 and so on?

### ISSUE THREAD

**Issue by Reinmar** [cksource/docs-builder#37]
A guide will look like this:

```md
...
some metadata
...
- - -
# Title of this page

## First Subtitle
```

Since `<h1>` is taken by the website title ("CKEditor 5 documentation"), the "Title of this page" should become `<h2>`. Is it possible to make this automatically?

**Comment by pomek** [comment]
Yes, we can.

**Comment by Reinmar** [comment]
So, I added it to `0.0.1`. Just please don't do this with regexp, cause it's gonna break in some code samples :D.
