### ISSUE TITLE
Dev: Generate the unique links in menu

### ISSUE THREAD

**Issue by pomek** [cksource/docs-builder#40]
In order to avoid situation like this:

![Bad menu...](https://cloud.githubusercontent.com/assets/156149/18626011/9696a5ce-7e52-11e6-88ad-15d77ceac56f.png) 

I mean multiple class `active`, the "dev" template should contain unique URLs (the same as the production version).

**Comment by Reinmar** [comment]
#41 broke samples - the code samples at the end are empty.

**Comment by Reinmar** [comment]
Besides, this error was actually visible in linter results. Don't you have hooks installed?

**Comment by pomek** [comment]
Fixed in https://github.com/cksource/docs-builder/commit/e3e9f0d0b7d6eaf230539c746d66c9f1fc5f98df.

> Don't you have hooks installed?

I have and I cannot explain what's happened.
