### ISSUE TITLE
UX problem with distingusing between links and categories in the left menu

### ISSUE THREAD

**Issue by Reinmar** [cksource/docs-builder#48]
Currently, real links (links to articles) and names of groups look identically, so you don't know what you can actually click (you have to hover).

Since we don't expect that names of groups will ever be clickable, we should style them differently than the links, I guess.

<img width="300" alt="screen shot 2016-09-20 at 16 18 35" src="https://cloud.githubusercontent.com/assets/156149/18674055/327c4588-7f4e-11e6-8186-6117ed1ea4e6.png">

**Comment by postJScriptum** [comment]
We could change category text color and add some "parent element" sign, like caret down:
<img width="189" alt="screen shot 2016-09-21 at 11 51 57" src="https://cloud.githubusercontent.com/assets/8529247/18706480/74db3ade-7ff2-11e6-8cd1-eba32d3a1a85.png">

Or maybe parent element should be also clickable. Link will be redirect user to listing of subpages like here: http://redux.js.org/docs/basics/.

**Comment by pomek** [comment]
> Or maybe parent element should be also clickable. Link will be redirect user to listing of subpages like here

I would like to avoid this. It introduces a lot of complication and… to be honest, we gain nothing. 
We can consider this option in the future, but at this moment I prefer to choose something easier to implement.

**Comment by Reinmar** [comment]
Making the parent elements clickable means that all parent elements must be clickable. We can't make this inconsistent.

And from my experience, you sometimes would like to put some content there and sometimes you don't know what to put there. So I'm rather leaning towards non-clickable, because you can always add a first child item like "Introduction". We did this in http://docs.ckeditor.com.

**Comment by Reinmar** [comment]
The idea with using triangles for "parent element" doesn't convince me cause they look a bit like "you can fold me and the triangle will rotate". Wrong connotation.

**Comment by postJScriptum** [comment]
Ok, so the parent elements will be non-clickable

> The idea with using triangles for "parent element" doesn't convince me cause they look a bit like "you can fold me and the triangle will rotate". Wrong connotation.

I have the same thoughts about this ico, it was just a proposal and I still think how show that this is non-clickable parent element.

**Comment by postJScriptum** [comment]
Next proposals:

With light, thin category labels and added left border to nested group of links:
![screen shot 2016-09-21 at 15 40 52](https://cloud.githubusercontent.com/assets/8529247/18713264/f18641b8-8011-11e6-8e12-bc24aea654fc.png)

With light and thin category labels:
![screen shot 2016-09-21 at 15 39 48](https://cloud.githubusercontent.com/assets/8529247/18713268/f7e1c064-8011-11e6-9f67-893b02c56f8c.png)

**Comment by Reinmar** [comment]
I think this is a bit more tricky and I don't like any of the proposals (plus, I don't have any idea myself), so let's ask @RyszardB for help.

**Comment by Reinmar** [comment]
I think that the current styling is OK for now.
