### ISSUE TITLE
Configuring the sitemap (menus and categories)

### ISSUE THREAD

**Issue by Reinmar** [cksource/docs-builder#50]
The documentation contains API docs and textual content (articles). We need an ability to structure the articles freely. At the same time, there can't be a centralised configuration because the documentation will come from many independent repositories. There are also additional requirements, like immutability of URLs (they should not change when an article is moved between categories).

Note: I treat samples as articles. So articles == current samples + current guides.

Structure:

1. Categories. E.g. "Quick Reference", "Guides", "Samples". The list of categories should be displayed in the top menu.
2. Path. [1-2] level deep path to an article. Path makes the structure in the left menu. First level makes  for the top items, optional 2nd level for 2nd level items and finally there are articles.

This means that for each MD file we need these things to be defined: category and path.

Additionally, each MD file has a title, which should be taken from the first heading defined inside it. It can also have some metadata like keywords.

## Solution

repository A (`ckeditor5-a`):

```
docs/
  config.json
  samples/
    foo.md
  guides/
    bar.md
    bom.md
```

repository B:

```
docs/
  config.json
  samples/
    x.md
  guides/
    y.md
    z.md
```

Example of `foo.md` (no magic):

```md
# Foo

... Content

## Heading which will become a h3

... Content
```

And an example `config.json`:

```json
{
  "samples/x": {
    "category": "Samples",
    "path": [ "Features" ],
    ... additional info
  },
  "guides/bar": {
    "category": "Quick Reference",
    "path": [ "HowTos", "Something" ],
    ... additional info
  },
  ...
}
```

Each repository will bring its own config. It means that the output must be a combination of all these configs.

A URL to "samples/x" will be: `/docs/a/samples/x.html`. In the future, we may allow overriding this through the config.

**Comment by pomek** [comment]
Generally, I totally agree with you. I was also thinking about creating a config file for each repository. 

It allows:

* simplifying the MD files (no additional metadata),
* having one place with a configuration for all files,
* introducing some configuration for a repository, e.g. `repositoryUrl` for ["edit this page"](https://github.com/cksource/docs-builder/issues/22) feature.

We should consider how to merge these `config.json` files. I mean an order of files after merging the configs into single a configuration.

I have also one question about an MD file:

```md
# Foo 

... Content

## Heading which will become a h3

... Content
```
Will `Foo` become an h2, or not?

**Comment by Reinmar** [comment]
I think that repos should be sorted by their names and that's it. The rest should be merged in the order in which things were defined in the `config.json`. Usually, only the -core or -engine repos will document things which need to be put in one category. Plus, e.g. in case of samples, we'll have simply a long list of features, which should be sorted by name (cause only that makes sense).

In the future, we may add support for `priority` property which will affect the sorting.

**Comment by Reinmar** [comment]
> Will Foo become an h2, or not?

Yes, because the page title should be `<h2>`.

**Comment by pomek** [comment]
Sounds good.
