### ISSUE TITLE
Links to static class properties

### ISSUE THREAD

**Issue by Reinmar** [cksource/docs-builder#74]
see in https://github.com/ckeditor/ckeditor5-core/commit/cd70e4a037a2906e10fd68830db3a093eca842bd#diff-a4f485aa834ca5b3c24819fceb39c56fR23

`{@link .requires}`, `{@link ~Plugin.requires}` didn't work.

**Comment by ma2ciek** [comment]
I probably forgot to implement this. It requires about an hour to work and be covered by tests.

**Comment by ma2ciek** [comment]
I see that the second example works here: https://github.com/ckeditor/ckeditor5-ui/blob/master/src/template.js#L1605 (https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/api/module_ui_template-Template.html#bind)

Is the issue still valid?

**Comment by pomek** [comment]
I guess this project is not valid anymore.

**Comment by ma2ciek** [comment]
> I guess this project is not valid anymore.

I know that. But we can move valid tickets to `ckeditor5-dev`

**Comment by Reinmar** [comment]
I don't know. But let's not spend time on this because I don't recall some blocking issues (you can always use the full path).
