### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by Reinmar** [cksource/docs-builder#8]
That's how the page should look like:

![docs_pt-sans](https://cloud.githubusercontent.com/assets/156149/18439782/ea8b20ca-7906-11e6-9f15-104468fca313.png)

This is how it looks like now:

![screen shot 2016-09-12 at 16 35 35](https://cloud.githubusercontent.com/assets/156149/18439804/f882fdd8-7906-11e6-9c3d-0cee6199ac63.png)

Issues which I noticed:

* Wrong background color for items in the left menu.
* Wrong font color (everywhere).
* Wrong font size in the ToC.
* Wrong font-weight in the top menu.
* Too big "CKEditor 5" in the top bar.
* Doubled border on the left side of ToC.
* Too big margin on the left side of the ToC.
* Wrong margins between items in the ToC.
* Too dark arrow icons.
* Far too high items in the left menu.
* Code samples were meant to have dark background.

Other issues are related to RWD:

* The middle column was supposed to scale together with the window up to some max width (which makes sense for it. See how it works on http://docs.ckeditor.com now.
* No version for small screens.

**Comment by postJScriptum** [comment]
@Reinmar please check what should be improved in current version.

**Comment by Reinmar** [comment]
Please put it on review, then :)
