### ISSUE TITLE
Code samples are incorrectly formatted

### ISSUE THREAD

**Issue by Reinmar** [cksource/docs-builder#9]
![screen shot 2016-09-13 at 13 13 45](https://cloud.githubusercontent.com/assets/156149/18471820/f42e237c-79b3-11e6-81c6-74696c9a1bae.png)

**Comment by pomek** [comment]
Fixed in #6.

Now, it looks:

![image](https://cloud.githubusercontent.com/assets/2270764/18475623/78e417f8-79c7-11e6-9388-643ff06edbe6.png)
